require('dotenv')
    .config();
const swagger = require('swagger-autogen')();

const path = './src/doc/swagger_output.json';
const routes = ['./src/routes.js'];

const options = {
    info: {
        version: '1.0.0',
        title: 'to LinkApi(PipeDrive + Bling)',
        description: 'Documentation Generated By Swagger for to LinkApi(PipeDrive + Bling)'
    },
    host: `${process.env.SWAGGER_URI}`,
    basePath: '',
    schemes: ['http', 'https']
};

swagger(path, routes, options)
    .then(() =>{
        require('./server.js');
    });